### ISSUE TITLE
Go get problem

### ISSUE THREAD

**Issue by cajund** [gonum/gonum#1311] opened 2020-04-15 18:00 UTC
```
$ go get -u gonum.org/v1/gonum/...
# gonum.org/v1/gonum/lapack/gonum
../go/src/gonum.org/v1/gonum/lapack/gonum/lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )
# gonum.org/v1/gonum/lapack/testlapack
../go/src/gonum.org/v1/gonum/lapack/testlapack/general.go:22:15: syntax error: unexpected p, expecting semicolon or newline or )
```
Anyone report this to you yet? I just ran this a few minutes ago.

Thanks.

**Comment by sbinet** [comment] 2020-04-15 18:01
duplicate of #1283

**Comment by sbinet** [comment] 2020-04-15 18:02
(feel free to reopen if that's not the case)

**Closed by sbinet** 2020-04-15 18:02 UTC
