### ISSUE TITLE
Error running go get ...

### ISSUE THREAD

**Issue by carlca** [gonum/gonum#238] opened 2017-09-17 12:02 UTC
Golang 1.9
macOS 10.12.6

Hello, I've just downloaded Gonum and run 
`go get -u -t gonum.org/v1/gonum/...`. 

I got the error message 
`package gonum.org/v1/gonum/blas/gonum/internal/math32: cannot find package "gonum.org/v1/gonum/blas/gonum/internal/math32" in any of:
	/usr/local/go/src/gonum.org/v1/gonum/blas/gonum/internal/math32 (from $GOROOT)
	/Users/carlca/Code/go/src/gonum.org/v1/gonum/blas/gonum/internal/math32 (from $GOPATH)`.

I then ran `go test gonum.org/v1/...` and got either `?` or `ok`, so on the face of it, the tests appeared to run ok. Should I be concerned about the initial error message? 

My go env is:

```
GOARCH="amd64"
GOBIN="/Users/carlca/Code/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/carlca/Code/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1d/1rqcnlq51zd4j_vqhp1kv3540000gp/T/go-build735349917=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```
Apologies for the bad formatting. The Github issues editor seems to be playing up.

**Comment by btracey** [comment] 2017-09-17 13:40
I can't replicate this. I'm on Go 1.9 osx 10.11.6.

I'm very confused about the error you're getting, because that package doesn't exist. I confirmed with a grep that `gonum.org/v1/gonum/blas/gonum/internal/math32` doesn't appear anywhere in the suite and you can see from https://github.com/gonum/gonum/tree/master/blas/gonum that the package isn't there.

**Comment by carlca** [comment] 2017-09-17 16:17
internal/math32 is certainly there...

![screen shot 2017-09-17 at 17 18 31](https://user-images.githubusercontent.com/260612/30522683-0e509150-9bcc-11e7-9e19-41eb42d7b5d5.png)

**Comment by carlca** [comment] 2017-09-17 16:18
But not under `blas` ...

**Comment by btracey** [comment] 2017-09-17 16:18
yes, but your error isn't about `gonum.org/v1/gonum/internal/math32`, it's about `gonum.org/v1/gonum/blas/gonum/internal/math32`  (notice the extra `blas/gonum`)

**Comment by carlca** [comment] 2017-09-17 16:20
Well, it's coming from somewhere!!

**Comment by btracey** [comment] 2017-09-17 16:22
Have you tried deleting your `pkg` directory? Maybe you have something cached there?

**Comment by btracey** [comment] 2017-09-17 16:23
Or deleting your repo and downloading fresh?

**Comment by carlca** [comment] 2017-09-17 16:28
Deleting the pkg folder and re-running the go get command seemed to get rid of the error. I don’t understand how a previously cached value can have caused the problem since I have never installed Gonum before. Thanks!

**Comment by kortschak** [comment] 2017-10-25 04:00
Closing since this seems to be fixed.

**Closed by kortschak** 2017-10-25 04:00 UTC
