### ISSUE TITLE
meta-issue: document deprecation of all old gonum/xyz repos

### ISSUE THREAD

**Issue by sbinet** [gonum/gonum#108] opened 2017-06-26 15:41 UTC
(putting it there, feel free to redirect to the best place)

we should clearly put on all the old `gonum/xyz` repositories' `README.md` that these repos are deprecated and that issues, PRs should be redirected at `gonum/gonum`.

I don't think we clearly communicated this.

**Comment by btracey** [comment] 2017-06-26 15:43
Yep. We should probably do something along the lines of the Go team for the PRs, and have a "no longer accepting PRs" and "do not file issues"

We can't quite make it blank because the old issues are still a good reference.

**Comment by kortschak** [comment] 2017-06-26 20:04
The issue template and CONTRIBUTING.md could say this

--
afk
Dan

________________________________

**Comment by vladimir-ch** [comment] 2017-08-08 20:42
Haven't this been done?

**Comment by sbinet** [comment] 2017-08-08 21:10
Well, you can of course import, say, 'gonum.org/v1/plot' it itself will import 'github.com/gonum/plot/vg' so you'll end up with a bit of a mess...

**Comment by sbinet** [comment] 2017-08-08 21:14
(sorry, ignore my previous comment, I thought I was replying/commenting on another issue ... It's getting late over here..)

**Comment by kortschak** [comment] 2017-08-08 23:55
>Haven't this been done?

Largely. We probably want a notice on the package doc comments as well.

**Comment by vladimir-ch** [comment] 2018-11-18 19:55
The repositories would have to be unarchived in order to push the package doc updates to them. Do we want to go through this? Although tedious I would do it but I don't have rights to unarchive.

**Comment by kortschak** [comment] 2018-11-18 21:15
I've been thinking about this recently too; there is a new feature where bugs can be migrated between repos. This might be worth doing, but will require a reasonable level of curation. Perhaps we can unarchive, add notes to the docs and README and leave it open for a week or two to let people do migration and then re-archive.

**Comment by vladimir-ch** [comment] 2018-11-19 13:53
Maybe I simplify it too much but why not just unarchive, send PRs that add or update the package docs, merge them and then archive again?

**Comment by kortschak** [comment] 2018-11-19 20:52
I was thinking of taking the opportunity to move some issues that are still useful to the core repo (the outstanding dynamic path finding issues in graph are an example of this, but there are others).

**Comment by vladimir-ch** [comment] 2018-11-20 13:58
I see. Then let's go through the repositories one by one?

**Comment by kortschak** [comment] 2018-11-21 07:31
Do you have a preference for where to start?

**Comment by vladimir-ch** [comment] 2018-11-21 09:36
Not really. Let's go in the default order of https://github.com/gonum?utf8=%E2%9C%93&q=&type=archived&language=

**Comment by kortschak** [comment] 2018-11-21 09:42
Done. mathext is open.

**Comment by kortschak** [comment] 2018-11-21 09:59
optimize is open. I'll leave you to go through the issues and migrate them as you see fit.

**Comment by vladimir-ch** [comment] 2018-11-21 10:20
The "Transfer this issue" button does not appear for me.

Do we want to address all issues in the old repositories, either by closing or transferring?

**Comment by kortschak** [comment] 2018-11-21 10:36
I think we do want to either close or transfer.

It seems the transfer butter is part of the admin role.

**Comment by vladimir-ch** [comment] 2018-11-22 05:57
I cannot transfer the last issue from optimize. It says that my browser did something unexpected. Could you please try transferring it?

**Comment by kortschak** [comment] 2018-11-22 06:31
Same for me. I suspect that it's an issue with the user no longer existing. I'll contact support.

**Comment by kortschak** [comment] 2018-11-22 20:03
They have seen this problem before. We can either close it there or come back to it later when the issue is fixed.

**Comment by vladimir-ch** [comment] 2018-11-22 20:57
I think we can close it and go to the next repository.

What about the pull requests?

**Comment by kortschak** [comment] 2018-11-22 21:02
I don't think we really need to worry about them do we?

**Comment by vladimir-ch** [comment] 2018-11-22 21:29
I was just asking in case we want to end up in clean state. I think it would actually make sense to close them.

**Comment by kortschak** [comment] 2018-11-22 22:12
Yeah, that's fine by me. Though a clean slate is not really what we are going to get; the closed PRs and issues are still valuable.

**Comment by kortschak** [comment] 2018-11-22 22:29
Fair enough. SGTM

**Comment by kortschak** [comment] 2018-11-25 07:49
@vladimir-ch @btracey Do either of you want to migrate the remaining issue in gonum/diff?

**Comment by vladimir-ch** [comment] 2018-11-25 07:52
I will migrate it.

**Comment by vladimir-ch** [comment] 2018-12-09 23:14
I think that all packages have been handled except for `stat` and `graph` which both have an outstanding PR waiting for a decision.

**Comment by kortschak** [comment] 2018-12-09 23:18
Both of those are waiting for @btracey.

**Comment by kortschak** [comment] 2018-12-22 21:16
Thanks for cleaning up those things.

**Closed by kortschak** 2018-12-22 21:16 UTC
