### ISSUE TITLE
Dejkstra newAllShortest: runtime.MemStats.Sys leak

### ISSUE THREAD

**Issue by savalin** [gonum/gonum#1174] opened 2019-11-19 13:27 UTC
### What are you trying to do?
My app needs to rebuild dejkstra allShortest by updated edges data during its lifetime.

### What did you do?
After a few rebuilds, I noticed that the app consumes memory more and more. Code inspection leads nothing... It creates a new instance of WeightedDirectedGraph and calculates DijkstraAllPaths, there's no link to old data.
I wrote a simple example to check if this clean version will leak.

### What did you expect to happen?
The app consumes the same amount of memory after graph re-init (approximately, using same dataset).

### What actually happened?
After each graph re-init, we got increasing memory consumption and it's not freed.

>  => loading graph: 1 time
> Alloc = 7076 MiB        TotalAlloc = 7087 MiB   **Sys = 7404 MiB**  HeapInuse = 7081 MiB        **HeapSys = 7103 MiB**  HeapIdle = 22 MiB   HeapReleased = 22 MiB       StackInuse = 0  StackSys = 0    NumGC = 6
>
>  => loading graph: 2 time
> Alloc = 7076 MiB        TotalAlloc = 14163 MiB  **Sys = 12060 MiB** HeapInuse = 7082  MiB       **HeapSys = 11583 MiB** HeapIdle = 4501 MiB HeapReleased = 265 MiB      StackInuse = 0  StackSys = 0    NumGC = 7
> => loading graph: 3 time
> Alloc = 7076 MiB        TotalAlloc = 21240 MiB  **Sys = 12069 MiB** HeapInuse = 7083 MiB        **HeapSys = 11583 MiB** HeapIdle = 4499 MiB HeapReleased = 458 MiB      StackInuse = 0  StackSys = 0    NumGC = 9
> 
> ..
> => loading graph: 6 time
> Alloc = 7076 MiB        TotalAlloc = 42469 MiB  **Sys = 15505 MiB** HeapInuse = 7083        **HeapSys = 14911** HeapIdle = 7828 HeapReleased = 3573     StackInuse = 0  StackSys = 0    NumGC = 17

runtime.MemStats.Sys is increasing

### What version of Go and Gonum are you using?
Go version: v1.13.4
gonum version: v0.6.0

### Does this issue reproduce with the current master?
Yes.

### Code example
```
import (
	"bufio"
	"fmt"
	"io/ioutil"
	"math"
	"os"
	"runtime"

	graphPath "gonum.org/v1/gonum/graph/path"
	"gonum.org/v1/gonum/graph/simple"
)

func main() {
	var file, err = os.Open("edges_dump.json")
	if err != nil {
		panic(err)
	}

	var b []byte
	if b, err = ioutil.ReadAll(file); err != nil {
		panic(err)
	}

	var edges model.Edges
	if err = edges.Unmarshal(b); err != nil {
		panic(err)
	}

	log("JSON parsed! %d edges found.", len(edges))

	i := 1

	input := bufio.NewScanner(os.Stdin)
	for {
		log("Press Enter to start loading")
		input.Scan()

		log("  => loading graph: %d time", i)

		printMemUsage()

		dg := simple.NewWeightedDirectedGraph(0, math.Inf(1))

		// add edges to graph (for same edges use less weight)
		for _, e := range edges {
			if e.StartPointID == e.EndPointID {
				continue
			}

			var weight float64 = 99999 // no distance - no trip
			if e.RouteMapWeight > 0 {
				weight = float64(e.RouteMapWeight)
			}

			w, ok := dg.Weight(e.StartPointID, e.EndPointID)
			if ok && w <= weight {
				continue
			}

			weightedEdge := dg.NewWeightedEdge(simple.Node(e.StartPointID), simple.Node(e.EndPointID), weight)
			dg.SetWeightedEdge(weightedEdge)
		}

		log("  => DG created!")
		printMemUsage()

		allShortest := graphPath.DijkstraAllPaths(dg)

		log("  => all shortest created!")
		printMemUsage()

		path, weight, unique := allShortest.Between(2, 3)

		// just to escape 'unused variables' error
		log("  => path: %v, weight: %f, unique: %t\n", path, weight, unique)

		i++
	}
}

func log(s string, args ...interface{}) {
	fmt.Printf(s+"\n", args...)
}

func printMemUsage() {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	// https://golang.org/pkg/runtime/#MemStats
	fmt.Printf("==================================\n")
	fmt.Printf("Alloc = %v MiB", bToMb(m.Alloc))
	fmt.Printf("\tTotalAlloc = %v MiB", bToMb(m.TotalAlloc))
	fmt.Printf("\tSys = %v MiB", bToMb(m.Sys))
	fmt.Printf("\tHeapInuse = %v MiB", bToMb(m.HeapInuse))
	fmt.Printf("\tHeapSys = %v MiB", bToMb(m.HeapSys))
	fmt.Printf("\tHeapIdle = %v MiB", bToMb(m.HeapIdle))
	fmt.Printf("\tHeapReleased = %v MiB", bToMb(m.HeapReleased))
	fmt.Printf("\tStackInuse = %v MiB", bToMb(m.StackInuse))
	fmt.Printf("\tStackSys = %v MiB", bToMb(m.StackSys))
	fmt.Printf("\tNumGC = %v\n", m.NumGC)
	fmt.Printf("==================================\n")
}

func bToMb(b uint64) uint64 {
	return b / 1024 / 1024
}

```

**Comment by vladimir-ch** [comment] 2019-11-19 17:28
Does the value of `MemStats.HeapSys` eventually settle at a value? In my quick test with a graph generated by `gonum.org/v1/gonum/graph/graphs/gen` it increases but in the end stays constant after 4-5 iterations. The number of iterations seems to increase for larger graphs, so in your case it may take longer.

I don't know enough about Go runtime, how it allocates memory and whether it is affected by things like memory fragmentation but to me this increase (which in the end levels off) looks like the way the Go memory allocator works (for allocation patterns that your use-case produces) and not like an issue.

**Comment by vladimir-ch** [comment] 2019-11-19 17:39
I've just noticed that you mention "leak" in the issue title. This is not a leak. Notice that `Alloc` is constant and what the documentation says about `HeapSys`:
```
// HeapSys estimates the largest size the heap has had.
```

**Comment by kortschak** [comment] 2019-11-19 19:26
Can you post a self-contained reproducer? The code above depends on your edge file.

**Comment by savalin** [comment] 2019-11-20 11:21
@kortschak I've created a small repo https://github.com/savalin/exapmle where I committed the full code and edges dump.
Is it enough?

**Comment by savalin** [comment] 2019-11-20 11:50
btw it seems similar https://blog.cloudflare.com/recycling-memory-buffers-in-go/
Maybe it could help somehow.

**Comment by kortschak** [comment] 2019-11-20 19:30
Yeah, this is not a leak, it's just a consequence of the way the GC works. There's really nothing we can do about this in graph (we go to lengths to avoid allocation in floats, mat, blas and lapack and also to a degree in stat), but graph is much more difficult because of the dynamic nature of the constructs and that users have access to the values that get allocated by the packages (this means `sync.Pool` is not appropriate). Note that I do make fairly substantial efforts to reduce allocations in graph, it's just that this is much harder.

If this is causing you a problem, it would be best to ask at go-nuts or file an issue against the language (probably in that order).

**Comment by savalin** [comment] 2019-11-26 15:53
Thank you for investigation.
Currently, we found the only one workaround: downgrade golang to v1.11.*

Tried the following things:
- compilation using go 1.12.13, 1.13.4, master (go1.4-bootstrap-20170531)
- gonum forking, implementation Flush() methods for WeightedDirectedGraph/AllShortest internal slices and maps force delete (and it helped for the case when we don't have two graphs in memory at same time)
- manual runtime.GC() / debug.FreeOSMemory() calls
- GODEBUG=madvdontneed=1

**Comment by kortschak** [comment] 2019-12-04 21:46
It looks like this is being handled at golang/go, so closing this. Please comment here again if we need to do more.

**Closed by kortschak** 2019-12-04 21:46 UTC
