### ISSUE TITLE
proposal: mat: rename Symmetric method to avoid name conflict when embedding mat.Symmetric

### ISSUE THREAD

**Issue by deasmhumhna** [gonum/gonum#1532] opened 2020-12-25 17:00 UTC
Trying to embed mat.Symmetric in another struct
```
type SymmetricLinOp struct {
    mat.Symmetric
}
```
 and get a `SymmetricLinOp.Symmetric is a field, not a method` error during compilation. I suppose this is why the "-er" suffix rule is often used, to avoid this kind of issue. Obviously, I can just make a named field and write wrappers for all the relevant methods, but that's a bit of a waste.

**Comment by kortschak** [comment] 2020-12-25 21:31
Can you paste a reproducer just so we can see the impact.

The obvious work-around for this is to define a local renaming of `mat.Symmetric`, say `type symmetric = mat.Symmetric` and then `type SymmetricLinOp struct { symmetric }`. This is not ideal, but workable. The fix would be to rename the `Symmetric` method, but that's a big change in terms of API breakage, so it needs to be considered carefully (if we were to do this, I would suggest something like `SymDim() int`)

**Comment by deasmhumhna** [comment] 2020-12-31 10:01
```
package main

import (
	"gonum.org/v1/gonum/mat"
)

type SymLinOp interface {
	mat.Symmetric
	MulVecTo(dst *mat.VecDense, _ bool, x mat.Vector)
}

type SymmetricWrapper struct {
	mat.Symmetric
}

func (m *SymmetricWrapper) MulVecTo(dst *mat.VecDense, _ bool, x mat.Vector) {
	dst.MulVec(m.Symmetric, x)
}

func takesSymLinOp(s SymLinOp) {}

func main(){
	s := mat.NewSymDense(3, []float64{2, 1, 1, 0, 2, 1, 0, 0, 2})
	w := &SymmetricWrapper{s}
	takesSymLinOp(w)
}
```

**Comment by kortschak** [comment] 2020-12-31 22:02
Yes. As mentioned above this can be fixed with a type alias.

```
package main

import "gonum.org/v1/gonum/mat"

type SymLinOp interface {
	mat.Symmetric
	MulVecTo(dst *mat.VecDense, _ bool, x mat.Vector)
}

type symmetric = mat.Symmetric

type SymmetricWrapper struct {
	symmetric
}

func (m *SymmetricWrapper) MulVecTo(dst *mat.VecDense, _ bool, x mat.Vector) {
	dst.MulVec(m, x)
}

func takesSymLinOp(s SymLinOp) {}

func main() {
	s := mat.NewSymDense(3, []float64{2, 1, 1, 0, 2, 1, 0, 0, 2})
	w := &SymmetricWrapper{s}
	takesSymLinOp(w)
}
```

This is clearly not ideal since it would need to be explained somewhere since it's probably not obvious to many people.

The alternative is similarly unpleasant in that is breaks the API (we already do this in the current phase of development, but this is — without hard data to back up the claim — probably likely to break more people than other breakages we've done recently). Despite that, I think that the pain of breakage once is likely to be less than the ongoing pain of explaining this in the future. Having said that, it does need to be discussed. Not least to figure out what a good name for the method would be (I suggested `SymDim` above, but that clashes with the naming convention of `Triangle` and `Bandwidth` for the triangular and banded matrix types both of which I think are good names). Some options:

- `SymDim`
- `SymmetricDim`
- `Size`
- `SymmetricSize`

None of these stand out as an obvious winner (_maybe_ `SymmetricDim`?)

/cc @vladimir-ch @btracey @sbinet

**Comment by soypat** [comment] 2021-06-04 20:37
`Symmetric` as a method that returns dimensions is confusing, I'm glad you are considering changing it! `SymDim` looks good to me, retains the sweet and short sound of `Dims()`.

**Comment by kortschak** [comment] 2021-08-16 03:43
Is there a decision here? v0.10.0 is coming soon.

**Comment by vladimir-ch** [comment] 2021-08-16 21:52
Sorry, I forgot about this one. `SymmetricDim` or `SymDim` both seem ok. In addition to those, how about `Symmetry`? By not having the `Dim` suffix it matches with `Triangle` or `Bandwidth`.

**Comment by kortschak** [comment] 2021-08-16 22:18
I like `Symmetry`. I'll send a PR.

**Comment by kortschak** [comment] 2021-08-17 10:51
Actually. Having second thoughts. Symmetry brings to mind the group theory context.

**Comment by vladimir-ch** [comment] 2021-08-18 23:22
Sure, no problem, it was just an idea. `SymmetricDim` is good.

**Comment by kortschak** [comment] 2021-08-21 09:41
Do we want to do `Triangle`=>`TriangleDim` at the same time?

**Closed** 2021-08-22 21:32 UTC
Labels: stability

**Comment by kortschak** [comment] 2021-08-22 21:44
I don't think we do since `Triangle` also returns the triangle.

**Comment by vladimir-ch** [comment] 2021-08-22 21:45
Agreed.
